apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-test2-cephfs
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Mi
    storageClassName: ocs-external-storagecluster-cephfs
    volumeMode: Filesystem
kind: List
metadata:
  resourceVersion: ""
